### ISSUE TITLE
remove measurements in entities if a space is present

### ISSUE THREAD

**Issue by Shimorina** [WebNLG/WebNLG-Text-to-triples#2]
In WebNLG, some triples were manually modified to include measurement units. For example,

```
<mtriple>3Arena | height | 28.0 (metres)</mtriple>
```
That was not done consistently. I was thinking of remedying this problem by modifying the evaluation scripts so that they don't take into account the measurement units.

Suggestion: convert such triples both in references and hypotheses to triples without measurement units (`<mtriple>3Arena | height | 28.0</mtriple>`)

Such cases can be spotted if the following conditions are met:

- the object has a space
- the object is not in double quotes (i.e. it is not a string literal)
- it has parentheses

**Comment by Shimorina** [comment]
@TallChris91, can we close it? It was fixed by https://github.com/WebNLG/WebNLG-Text-to-triples/commit/0b8c131be11ce5c4e520f477fb32fafd7ac7011d, right?

**Comment by TallChris91** [comment]
Yeah, it's all fixed. :)
